baseURL = 'https://www.marginalia-search.com/'
languageCode = 'en-us'
title = 'Marginalia Search'
theme = 'marginalia-search'
sectionPagesMenu = 'main'

defaultContentLanguage = 'en'
[languages.en]

[markup.goldmark.renderer]
  unsafe = true

[minify]
  minifyOutput = true

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'

[languages]
  [language.en]
    title = 'Marginalia'
    description = 'RIP Memex'

[outputs]
  home = ["HTML", "JSON", "RSS"]

[params]
  author = 'Viktor Lofgren'
  title = 'Marginalia Search'
  description = ''
  googleFontsLink = false

[Params]
  description = "Marginalia Search" 
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["log", "recipes"]
